### ISSUE TITLE
Error: You must log in first. - When using environment variable to set CIRCLECI_TOKEN

### ISSUE THREAD

**Issue by markandersontrocme** [mrolla/terraform-provider-circleci#131]
We have had no issues with this provider up until recently (maybe related to the CircleCI security leak...). We are always getting this error when using the environment variable `CIRCLECI_TOKEN`:

```
│ Error: You must log in first.
│
│   with module.platforms.module.circleci.data.circleci_context.this,
│   on platforms/circleci/main.tf line 21, in data "circleci_context" "this":
│   21: data "circleci_context" "this" {
```

When I set the value in the provider block directly we don't get this error...

# Versions

Terraform v1.1.6

```
circleci = {
      source  = "mrolla/circleci"
      version = "0.6.1"
 }
```

**Comment by kelvintaywl** [comment]
hi @markandersontrocme just to confirm, would the value set in the block be the same value as stored in your `CIRCLECI_TOKEN` environment variable?

If they are not, likely the value stored under the `CIRCLECI_TOKEN` environment variable is no longer valid.

You can always confirm the validity of the CircleCI API token with:

```console
$ curl -H "Circle-Token: ${CIRCLECI_TOKEN}" https://circleci.com/api/v2/me
```

**Comment by markandersontrocme** [comment]
It seems to have resolved itself, most likely it was during the CircleCI breach and rotation.
