### ISSUE TITLE
Plans applied through mac M1 are not recognised as applied by mac running on intel CPUs

### ISSUE THREAD

**Issue by atmosx** [mrolla/terraform-provider-circleci#141]
Hello,

I'm using this plugin using two mac laptops. I'm working mainly on a macbook pro M1 with ARM64 CPU, however every now and then I have to do some work from an older macbook pro running on Intel (x86) CPU.

When I **create**, **plan** and **apply** resources using the M1 laptop the state looks fine. Now on the intel laptop, running `terraform plan` will show the circleCI resources - only the circleCI resources - as _new_ and will try to re-create them. Of course this will fail, as the env variables exists already.

This is a bit of a problem as some team members have mac with x86 CPUs and others have Macs with ARM CPUs. I have not tested what happens when running on linux but my guess is that this is a CPU specific more than OS specific issue.

Kind regards,

P.

**Comment by kelvintaywl** [comment]
hi there, would you know where your state is saved in?

in other words, is your Terraform state saved locally or via a remote backend (e.g., AWS S3)?
https://developer.hashicorp.com/terraform/language/settings/backends/configuration

If local, this is then not an issue with this Terraform provider (or any other provider);
local backends (default) mean the state is saved as a file on your local machine, and switching to other machines will see the issue you mentioned above 🤓 hope it helps!

**Comment by atmosx** [comment]
> hi there, would you know where your state is saved in?
> 
> 
> 
> in other words, is your Terraform state saved locally or via a remote backend (e.g., AWS S3)?
> 
> https://developer.hashicorp.com/terraform/language/settings/backends/configuration
> 
> 
> 
> If local, this is then not an issue with this Terraform provider (or any other provider);
> 
> local backends (default) mean the state is saved as a file on your local machine, and switching to other machines will see the issue you mentioned above 🤓 hope it helps!

Sorry for the late reply here. This is not a problem anymore for me.

The state was/is remote, stored in s3.

**Comment by kelvintaywl** [comment]
@atmosx thanks for the updates!
perhaps you can close this issue too then :)
