### ISSUE TITLE
Replace jszwedko/go-circleci with in house client

### ISSUE THREAD

**Issue by mrolla** [mrolla/terraform-provider-circleci#17]
`github.com/jszwedko/go-circleci` does not seem to move anywhere in supporting api version 1.1 (see #2). Also, to support #15, we need the `unfollow` endpoint which is not implemented yet (not sure if it's a 1.0 endpoint and so can be merged upstream there).

**Comment by tgermain** [comment]
Feel free to assign me as reviewer if you have a PR for it.

**Comment by tgermain** [comment]
How do you propose we work on this matter ? 
Should we base our client on `github.com/jszwedko/go-circleci` as a start and start adding our changes and the endpoint we miss for #15 ? 
Should we start from scratch ?

I have never made any API client so I'm not the best judge of the quality and extensibility of `github.com/jszwedko/go-circleci` client. I would say it's better to start with its base (which have some unit tests), add what we need and if we find it cumbersome to work on it, we can change it.

**Comment by mrolla** [comment]
I already have a prototype client (based on the one that was used before the switch to @jszwedko one) only covering the 3 endpoints we need for env vars. I'm currently adding more unit tests mostly covering error cases and then I'll submit a PR for you to check. Once we are satisfied with the result we can include the follow/unfollow endpoints as well.

**Comment by tgermain** [comment]
Ok, so minimal api client, opinionated as it is meant first to be use for the this TF provider. Sounds good !

**Comment by jszwedko** [comment]
:+1: definitely do whatever makes sense for this project, but I'm happy to help integrate needed endpoints into `github.com/jszwedko/go-circleci` to support this. I realize I've been dragging my feet with `v1.1` support as I haven't had a direct need for it but a terraform provider would be a motivating use case.

**Comment by martinssipenko** [comment]
Is this fixed by #44 now?

**Comment by bendrucker** [comment]
Yes
