### ISSUE TITLE
Terraform 0.12 support

### ISSUE THREAD

**Issue by jdahlin** [mrolla/terraform-provider-circleci#21]
When preparing to upgrade to Terraform 0.12, I get the following:

```
$ terraform 0.12checklist
After analyzing this configuration and working directory, we have identified some necessary steps that we recommend you take before upgrading to Terraform v0.12:

- [ ] Provider "circleci" may need to be upgraded to a newer version that supports Terraform 0.12. (Supported version information is not available for this provider.)
```

Would be nice to be able to upgrade and keep using circleci.

**Comment by tgermain** [comment]
There is already a PR for that : #19 (thanks @jamestoyer !)

But IMHO it is a huge PR which will require some testing.

**Comment by mrolla** [comment]
@jdahlin the PR is on its way to be merged, sorry for the delay!

**Comment by mrolla** [comment]
Version 0.2.0 has been released 🎉

**Comment by tgermain** [comment]
If you can edit the description of that release to mention that this release is compatible with TF 0.12 it would be nice !

**Comment by mrolla** [comment]
@tgermain done!
