### ISSUE TITLE
Provide binaries for Windows

### ISSUE THREAD

**Issue by aeneasr** [mrolla/terraform-provider-circleci#23]
It would be great if GitHub releases could provide binaries for more platforms, including e.g. Windows. You could automate that process quite easily with e.g. https://goreleaser.com !

**Comment by mrolla** [comment]
Hey @aeneasr, I've added cross compiled binaries for Windows as per https://github.com/mrolla/terraform-provider-circleci/commit/61f42fe7d4eb173495553028ba7efe66d99a93c6. I'm gonna release `0.2.2` later today and it would be nice if you could test them out and let me know of any issues you might find!

**Comment by mrolla** [comment]
Version `0.2.2` has been released and includes Windows binaries 🎉
