### ISSUE TITLE
Bad circleci default url

### ISSUE THREAD

**Issue by Niklv** [mrolla/terraform-provider-circleci#24]
It should be `https://circleci.com/api/v1.1/` with slash at end.

My workaround: 
```terraform
provider "circleci" {
  api_token    = "${var.circleci_token}"
  organization = "myorg"
  vcs_type     = "bitbucket"
  url          = "https://circleci.com/api/v1.1/"
}
```

**Comment by mrolla** [comment]
Thanks for reporting! Fixed in https://github.com/mrolla/terraform-provider-circleci/commit/a716906bc83d2ce54e554c4927d6bb30a55e894a. I'm gonna release `0.2.2` later today.
