### ISSUE TITLE
Error: json: cannot unmarshal array into Go value of type circleci.EnvVar

### ISSUE THREAD

**Issue by binarylogic** [mrolla/terraform-provider-circleci#25]
When I `plan` I get the following error:

```
Error: json: cannot unmarshal array into Go value of type circleci.EnvVar
```

I'm unsure how to get more info, but clearly it's not reading data from the Circle API properly.

**Comment by tgermain** [comment]
Hi,
Do you have a minimal example of the terraform code that produce this error ? If they are sensitive information you can strip them.

**Comment by binarylogic** [comment]
Hi, yes, it's pretty simple:

```
resource "circleci_environment_variable" "project_AWS_SECRET_ACCESS_KEY" {
  project = "project"
  name    = "AWS_SECRET_ACCESS_KEY"
  value   = aws_iam_access_key.my_project.secret
}
```

Initially we were able to plan and add the ENV var just fine, but subsequent plans for failing with the above error.

**Comment by tgermain** [comment]
Is `project` enable on CircleCI ?

I'm not sure of the behavior of CircleCI provider if you try to act on a project which is not already enable on CircleCI.

This provider cannot enable a project yet as per #15 but you can do it with the [webUI](https://circleci.com/docs/2.0/project-build/#adding-projects) in the meantime.

**Comment by binarylogic** [comment]
Yep, all projects referenced are enabled in CircleCI.

**Comment by binarylogic** [comment]
For anyone reading this, the error was related to circleci env resources in the state that no longer exist:

```
terraform state list | grep circle
```

And then `rm`ing the resources that no longer exist fixed this:

```
terraform state rm circleci_environment_variable.XXX
```

Sorry for the noise!
