### ISSUE TITLE
 Create new release

### ISSUE THREAD

**Issue by jamestoyer** [mrolla/terraform-provider-circleci#30]
There have been a bunch of changes to the provider recently. It'd be nice to get a new release done so it can be referenced rather than building a local copy

**Comment by mrolla** [comment]
Hey @jamestoyer sorry for the delay, I've been busy with all bunch of stuff. I meant to release after I updated the readme, but I didn't manage to yet. So, I just tagged v0.3.0 and will update the readme later.

**Comment by mrolla** [comment]
Version 0.3.0 released 🎉

**Comment by jamestoyer** [comment]
🎉 woo thank you 🙂
