### ISSUE TITLE
context resources not found

### ISSUE THREAD

**Issue by odedpriva** [mrolla/terraform-provider-circleci#36]
```bash
Error: Invalid resource type

  on modules/circleci/main.tf line 15, in resource "circleci_context" "foo":
  15: resource "circleci_context" "foo" {

The provider provider.circleci does not support resource type
"circleci_context".
```

```bash
Error: Invalid resource type

  on modules/circleci/main.tf line 19, in resource "circleci_context_environment_variable" "foo":
  19: resource "circleci_context_environment_variable" "foo" {
```

provider version: 0.3.0

**Comment by bendrucker** [comment]
That release predates the addition of these resources. If you build from `master` you should get them.

**Comment by odedpriva** [comment]
Thanks, 

This provider is very helpful, when do you think you will update the release ?

**Comment by bendrucker** [comment]
That’s a question for @mrolla (if you want to make me a maintainer I’m happy to take care of it). 

FWIW I haven’t been able to test out these resources yet on real world projects yet.

**Comment by odedpriva** [comment]
As you suggested, I build the provider from source and both resources worked as expected.

**Comment by mrolla** [comment]
Hey guys, I meant to release the new version sooner, but then work came in like a wrecking ball. The CI is broken after the changes for the context and I had no real time to really looking at why yet. There is one rogue acc test which for some reason is triggered on CI and it breaks. I will look at it later today hopefully :pray:

**Comment by bendrucker** [comment]
`v0.4.0` is published to the Terraform Registry, please go ahead and load it from there with Terraform 0.13! For 0.12 you can still download and install binaries manually.

https://registry.terraform.io/providers/mrolla/circleci/latest
