### ISSUE TITLE
Publish to the Terraform Registry

### ISSUE THREAD

**Issue by davearata-snorack** [mrolla/terraform-provider-circleci#37]
Currently if you want to use this module with terraform cloud you need to clone the repo, build and include the binary in vcs. It would be much easier to use this provider if it was available on through the terraform registry

**Comment by mrolla** [comment]
I have no experience with the Terraform Cloud, but releasing to the registry should be easy enough. I'll investigate!

**Comment by bendrucker** [comment]
I do, the tricky part of Terraform Cloud is just that the only decent way to get prebuilt plugins into the runtime environment is by using a Git submodule. You can embed it directly with your configuration as well but that permanently bloats your repo.

I haven't published anything to the (brand new) provider registry just yet, but have been meaning to dig in. If you have any trouble let me know. Or if you wanna move this repo to a GitHub org, I'm happy to work on it.

**Comment by TomTucka** [comment]
Hey! I've just come across this project! I also maintain a CircleCI provider that is already on the terraform registry (https://registry.terraform.io/providers/TomTucka/circleci/latest) I'm currently working on a go-client that supports the V2 CircleCI API and the goal is to make the provider use that client. I'm actively working on this on a daily basis so would you like to have a conversation about merging projects?

**Comment by mrolla** [comment]
Hey @TomTucka, I'm up for merging projects, this definitely will allow the project to move forward. Also, @bendrucker you offered to help, are you still up for the idea? Maybe creating an organization for the provider could be a good idea.

**Comment by TomTucka** [comment]
I think creating an organisation for one provider might be overkill, however, I will add you to all the repos as a contributor! My long term goal is to get the provider onto the terraform-providers organisation, I started speaking with some people at circleci about this too!

**Comment by bendrucker** [comment]
Yep, happy to continue helping wherever I can, feel free to add me

**Comment by bendrucker** [comment]
@mrolla If you add me as an admin on this repo I can get this worked out. Seems like you've already configured a suitable token in Circle.

**Comment by mrolla** [comment]
Thanks to @bendrucker, now the provider is published (https://registry.terraform.io/providers/mrolla/circleci/latest).

@TomTucka sorry for being very late in answering, I'm going to move the merging efforts discussion in another issue so this one can be closed.
