### ISSUE TITLE
Update context environment variables in place

### ISSUE THREAD

**Issue by brondum** [mrolla/terraform-provider-circleci#45]
Would be super cool if you could update a context item instead of deleting and recreating the context item every time.

**The Problem:**
The problem occurs when you are reading data from a dynamic source and putting into your CircleCI Context.
This will make the provider delete the context item and afterwards recreate it. That becomes a problem if you have a terraform job taking a bit of time. Then you stop people from using that value in the context while deploying.

**The Solution:**
Creating a update function in the provider, which does not delete the context item at the start of the Terraform Job.

Notes
I know that CircleCI does not have a patch/update endpoint in there API, that why you could make some kind of delete-apply function in the provider and maybe solve the issue that way.

**Comment by mrolla** [comment]
Hey all! I'm reopening and keeping this open till we tag and release the next version (soon, just need to sort dependencies first, @bendrucker #48).

Thanks!
